// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fixed_tree_geometry_cpp
Rcpp::List fixed_tree_geometry_cpp(Eigen::MatrixXd x, int depth, int r, std::string design, std::string cut_method, int seed, int ncores);
RcppExport SEXP _ResTree_fixed_tree_geometry_cpp(SEXP xSEXP, SEXP depthSEXP, SEXP rSEXP, SEXP designSEXP, SEXP cut_methodSEXP, SEXP seedSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< std::string >::type design(designSEXP);
    Rcpp::traits::input_parameter< std::string >::type cut_method(cut_methodSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(fixed_tree_geometry_cpp(x, depth, r, design, cut_method, seed, ncores));
    return rcpp_result_gen;
END_RCPP
}
// full_tree_validity_cpp
bool full_tree_validity_cpp(SEXP model);
RcppExport SEXP _ResTree_full_tree_validity_cpp(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(full_tree_validity_cpp(model));
    return rcpp_result_gen;
END_RCPP
}
// full_loglik_cache_info_cpp
Rcpp::List full_loglik_cache_info_cpp(SEXP model);
RcppExport SEXP _ResTree_full_loglik_cache_info_cpp(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(full_loglik_cache_info_cpp(model));
    return rcpp_result_gen;
END_RCPP
}
// fixed_tree_fit_cpp
Rcpp::List fixed_tree_fit_cpp(SEXP model, SEXP theta, const Eigen::Map<Eigen::MatrixXd> input_new, Rcpp::Nullable<Eigen::VectorXd> output_new, int ncores);
RcppExport SEXP _ResTree_fixed_tree_fit_cpp(SEXP modelSEXP, SEXP thetaSEXP, SEXP input_newSEXP, SEXP output_newSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type input_new(input_newSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Eigen::VectorXd> >::type output_new(output_newSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(fixed_tree_fit_cpp(model, theta, input_new, output_new, ncores));
    return rcpp_result_gen;
END_RCPP
}
// full_fit_engine_new_cpp
SEXP full_fit_engine_new_cpp(SEXP model, SEXP theta, int ncores);
RcppExport SEXP _ResTree_full_fit_engine_new_cpp(SEXP modelSEXP, SEXP thetaSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(full_fit_engine_new_cpp(model, theta, ncores));
    return rcpp_result_gen;
END_RCPP
}
// full_fit_engine_eval_cpp
Rcpp::List full_fit_engine_eval_cpp(SEXP handle, SEXP theta, const Eigen::Map<Eigen::MatrixXd> input_new, Rcpp::Nullable<Eigen::VectorXd> output_new);
RcppExport SEXP _ResTree_full_fit_engine_eval_cpp(SEXP handleSEXP, SEXP thetaSEXP, SEXP input_newSEXP, SEXP output_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type input_new(input_newSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Eigen::VectorXd> >::type output_new(output_newSEXP);
    rcpp_result_gen = Rcpp::wrap(full_fit_engine_eval_cpp(handle, theta, input_new, output_new));
    return rcpp_result_gen;
END_RCPP
}
// full_fit_engine_release_cpp
void full_fit_engine_release_cpp(SEXP handle);
RcppExport SEXP _ResTree_full_fit_engine_release_cpp(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    full_fit_engine_release_cpp(handle);
    return R_NilValue;
END_RCPP
}
// find_neigh
Rcpp::List find_neigh(const Eigen::MatrixXd& input, int r_knot);
RcppExport SEXP _ResTree_find_neigh(SEXP inputSEXP, SEXP r_knotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type input(inputSEXP);
    Rcpp::traits::input_parameter< int >::type r_knot(r_knotSEXP);
    rcpp_result_gen = Rcpp::wrap(find_neigh(input, r_knot));
    return rcpp_result_gen;
END_RCPP
}
// smc_engine_pmmh_cpp
Rcpp::List smc_engine_pmmh_cpp(SEXP handle, SEXP model, SEXP theta0, Rcpp::NumericVector u0, int n_iter, int burnin, Rcpp::NumericVector prop_sd, int sig2_moves, bool blocked, Rcpp::List prior, std::string adapt, double target_accept, int seed, int ncores, bool verbose, Rcpp::Nullable<Rcpp::NumericMatrix> input_new, Rcpp::Nullable<Rcpp::NumericVector> output_new, std::string point_estimate);
RcppExport SEXP _ResTree_smc_engine_pmmh_cpp(SEXP handleSEXP, SEXP modelSEXP, SEXP theta0SEXP, SEXP u0SEXP, SEXP n_iterSEXP, SEXP burninSEXP, SEXP prop_sdSEXP, SEXP sig2_movesSEXP, SEXP blockedSEXP, SEXP priorSEXP, SEXP adaptSEXP, SEXP target_acceptSEXP, SEXP seedSEXP, SEXP ncoresSEXP, SEXP verboseSEXP, SEXP input_newSEXP, SEXP output_newSEXP, SEXP point_estimateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type u0(u0SEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prop_sd(prop_sdSEXP);
    Rcpp::traits::input_parameter< int >::type sig2_moves(sig2_movesSEXP);
    Rcpp::traits::input_parameter< bool >::type blocked(blockedSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< std::string >::type adapt(adaptSEXP);
    Rcpp::traits::input_parameter< double >::type target_accept(target_acceptSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type input_new(input_newSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type output_new(output_newSEXP);
    Rcpp::traits::input_parameter< std::string >::type point_estimate(point_estimateSEXP);
    rcpp_result_gen = Rcpp::wrap(smc_engine_pmmh_cpp(handle, model, theta0, u0, n_iter, burnin, prop_sd, sig2_moves, blocked, prior, adapt, target_accept, seed, ncores, verbose, input_new, output_new, point_estimate));
    return rcpp_result_gen;
END_RCPP
}
// pmmh_predict_cpp
Rcpp::List pmmh_predict_cpp(SEXP model, SEXP theta, const Eigen::Map<Eigen::MatrixXd> chain, Rcpp::List history, Eigen::MatrixXd input_new, Rcpp::Nullable<Rcpp::NumericVector> output_new, int ncores);
RcppExport SEXP _ResTree_pmmh_predict_cpp(SEXP modelSEXP, SEXP thetaSEXP, SEXP chainSEXP, SEXP historySEXP, SEXP input_newSEXP, SEXP output_newSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type chain(chainSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type history(historySEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type input_new(input_newSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type output_new(output_newSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(pmmh_predict_cpp(model, theta, chain, history, input_new, output_new, ncores));
    return rcpp_result_gen;
END_RCPP
}
// smc_sample_cpp
Rcpp::List smc_sample_cpp(SEXP model, SEXP theta, int n_particles, int seed, int ncores, double temper_alpha, std::string resampling, Rcpp::Nullable<Eigen::MatrixXd> input_new, Rcpp::Nullable<Eigen::VectorXd> output_new);
RcppExport SEXP _ResTree_smc_sample_cpp(SEXP modelSEXP, SEXP thetaSEXP, SEXP n_particlesSEXP, SEXP seedSEXP, SEXP ncoresSEXP, SEXP temper_alphaSEXP, SEXP resamplingSEXP, SEXP input_newSEXP, SEXP output_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n_particles(n_particlesSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    Rcpp::traits::input_parameter< double >::type temper_alpha(temper_alphaSEXP);
    Rcpp::traits::input_parameter< std::string >::type resampling(resamplingSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Eigen::MatrixXd> >::type input_new(input_newSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Eigen::VectorXd> >::type output_new(output_newSEXP);
    rcpp_result_gen = Rcpp::wrap(smc_sample_cpp(model, theta, n_particles, seed, ncores, temper_alpha, resampling, input_new, output_new));
    return rcpp_result_gen;
END_RCPP
}
// smc_engine_new_cpp
SEXP smc_engine_new_cpp(SEXP model, int n_particles, std::string resampling, double temper_alpha, int ncores, double path_cache_mb, int keep_cache_levels, double keep_cache_mb, double task_budget_mb, double level_cache_mb);
RcppExport SEXP _ResTree_smc_engine_new_cpp(SEXP modelSEXP, SEXP n_particlesSEXP, SEXP resamplingSEXP, SEXP temper_alphaSEXP, SEXP ncoresSEXP, SEXP path_cache_mbSEXP, SEXP keep_cache_levelsSEXP, SEXP keep_cache_mbSEXP, SEXP task_budget_mbSEXP, SEXP level_cache_mbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< int >::type n_particles(n_particlesSEXP);
    Rcpp::traits::input_parameter< std::string >::type resampling(resamplingSEXP);
    Rcpp::traits::input_parameter< double >::type temper_alpha(temper_alphaSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    Rcpp::traits::input_parameter< double >::type path_cache_mb(path_cache_mbSEXP);
    Rcpp::traits::input_parameter< int >::type keep_cache_levels(keep_cache_levelsSEXP);
    Rcpp::traits::input_parameter< double >::type keep_cache_mb(keep_cache_mbSEXP);
    Rcpp::traits::input_parameter< double >::type task_budget_mb(task_budget_mbSEXP);
    Rcpp::traits::input_parameter< double >::type level_cache_mb(level_cache_mbSEXP);
    rcpp_result_gen = Rcpp::wrap(smc_engine_new_cpp(model, n_particles, resampling, temper_alpha, ncores, path_cache_mb, keep_cache_levels, keep_cache_mb, task_budget_mb, level_cache_mb));
    return rcpp_result_gen;
END_RCPP
}
// smc_engine_logZ_cpp
Rcpp::NumericVector smc_engine_logZ_cpp(SEXP handle, SEXP theta, int seed, bool diagnostics);
RcppExport SEXP _ResTree_smc_engine_logZ_cpp(SEXP handleSEXP, SEXP thetaSEXP, SEXP seedSEXP, SEXP diagnosticsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type diagnostics(diagnosticsSEXP);
    rcpp_result_gen = Rcpp::wrap(smc_engine_logZ_cpp(handle, theta, seed, diagnostics));
    return rcpp_result_gen;
END_RCPP
}
// smc_engine_save_cpp
void smc_engine_save_cpp(SEXP handle);
RcppExport SEXP _ResTree_smc_engine_save_cpp(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    smc_engine_save_cpp(handle);
    return R_NilValue;
END_RCPP
}
// smc_engine_restore_cpp
bool smc_engine_restore_cpp(SEXP handle);
RcppExport SEXP _ResTree_smc_engine_restore_cpp(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(smc_engine_restore_cpp(handle));
    return rcpp_result_gen;
END_RCPP
}
// smc_engine_release_cpp
void smc_engine_release_cpp(SEXP handle);
RcppExport SEXP _ResTree_smc_engine_release_cpp(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    smc_engine_release_cpp(handle);
    return R_NilValue;
END_RCPP
}
// predict_state_cpp
Rcpp::List predict_state_cpp(SEXP state, const Eigen::Map<Eigen::MatrixXd> input_new, Rcpp::IntegerVector distinct_rep, Eigen::VectorXd w_distinct, double sig2, Rcpp::Nullable<Eigen::VectorXd> output_new, int ncores);
RcppExport SEXP _ResTree_predict_state_cpp(SEXP stateSEXP, SEXP input_newSEXP, SEXP distinct_repSEXP, SEXP w_distinctSEXP, SEXP sig2SEXP, SEXP output_newSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type state(stateSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type input_new(input_newSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type distinct_rep(distinct_repSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type w_distinct(w_distinctSEXP);
    Rcpp::traits::input_parameter< double >::type sig2(sig2SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Eigen::VectorXd> >::type output_new(output_newSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_state_cpp(state, input_new, distinct_rep, w_distinct, sig2, output_new, ncores));
    return rcpp_result_gen;
END_RCPP
}
// rebuild_state_cpp
SEXP rebuild_state_cpp(SEXP model, SEXP theta, const Eigen::Map<Eigen::MatrixXd> S, const Eigen::Map<Eigen::MatrixXd> J, const Eigen::Map<Eigen::MatrixXd> cuts);
RcppExport SEXP _ResTree_rebuild_state_cpp(SEXP modelSEXP, SEXP thetaSEXP, SEXP SSEXP, SEXP JSEXP, SEXP cutsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type J(JSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type cuts(cutsSEXP);
    rcpp_result_gen = Rcpp::wrap(rebuild_state_cpp(model, theta, S, J, cuts));
    return rcpp_result_gen;
END_RCPP
}
// rebuild_nodes_cpp
SEXP rebuild_nodes_cpp(SEXP model, SEXP theta, Rcpp::DataFrame nodes, int K);
RcppExport SEXP _ResTree_rebuild_nodes_cpp(SEXP modelSEXP, SEXP thetaSEXP, SEXP nodesSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type nodes(nodesSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(rebuild_nodes_cpp(model, theta, nodes, K));
    return rcpp_result_gen;
END_RCPP
}
// predict_structures_cpp
Rcpp::List predict_structures_cpp(SEXP model, SEXP theta, const Eigen::Map<Eigen::MatrixXd> input_new, const Eigen::Map<Eigen::MatrixXd> S, const Eigen::Map<Eigen::MatrixXd> J, const Eigen::Map<Eigen::MatrixXd> cuts, Eigen::VectorXd w, Rcpp::Nullable<Eigen::VectorXd> output_new, int ncores);
RcppExport SEXP _ResTree_predict_structures_cpp(SEXP modelSEXP, SEXP thetaSEXP, SEXP input_newSEXP, SEXP SSEXP, SEXP JSEXP, SEXP cutsSEXP, SEXP wSEXP, SEXP output_newSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type input_new(input_newSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type J(JSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type cuts(cutsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type w(wSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Eigen::VectorXd> >::type output_new(output_newSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_structures_cpp(model, theta, input_new, S, J, cuts, w, output_new, ncores));
    return rcpp_result_gen;
END_RCPP
}
// mixture_moments_cpp
Rcpp::List mixture_moments_cpp(const Eigen::Map<Eigen::MatrixXd> mean, const Eigen::Map<Eigen::MatrixXd> variance, const Eigen::VectorXd& w);
RcppExport SEXP _ResTree_mixture_moments_cpp(SEXP meanSEXP, SEXP varianceSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type variance(varianceSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(mixture_moments_cpp(mean, variance, w));
    return rcpp_result_gen;
END_RCPP
}
// restree_loglik
Rcpp::NumericVector restree_loglik(SEXP model, SEXP theta, Rcpp::Nullable<Rcpp::List> tree, Rcpp::Nullable<Rcpp::IntegerVector> nparticles, std::string resampling, double temper_alpha, int seed, int ncores, bool verify, bool diagnostics);
RcppExport SEXP _ResTree_restree_loglik(SEXP modelSEXP, SEXP thetaSEXP, SEXP treeSEXP, SEXP nparticlesSEXP, SEXP resamplingSEXP, SEXP temper_alphaSEXP, SEXP seedSEXP, SEXP ncoresSEXP, SEXP verifySEXP, SEXP diagnosticsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type nparticles(nparticlesSEXP);
    Rcpp::traits::input_parameter< std::string >::type resampling(resamplingSEXP);
    Rcpp::traits::input_parameter< double >::type temper_alpha(temper_alphaSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    Rcpp::traits::input_parameter< bool >::type verify(verifySEXP);
    Rcpp::traits::input_parameter< bool >::type diagnostics(diagnosticsSEXP);
    rcpp_result_gen = Rcpp::wrap(restree_loglik(model, theta, tree, nparticles, resampling, temper_alpha, seed, ncores, verify, diagnostics));
    return rcpp_result_gen;
END_RCPP
}
// score_mixture_cpp
Rcpp::List score_mixture_cpp(Rcpp::NumericVector y, Rcpp::NumericMatrix mean, Rcpp::NumericMatrix var, Rcpp::Nullable<Rcpp::NumericMatrix> df, Rcpp::NumericVector w, Rcpp::NumericVector probs, bool want_crps, bool want_logscore, bool want_cdf, double rel_tol, int subdivisions, int ncores);
RcppExport SEXP _ResTree_score_mixture_cpp(SEXP ySEXP, SEXP meanSEXP, SEXP varSEXP, SEXP dfSEXP, SEXP wSEXP, SEXP probsSEXP, SEXP want_crpsSEXP, SEXP want_logscoreSEXP, SEXP want_cdfSEXP, SEXP rel_tolSEXP, SEXP subdivisionsSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type var(varSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type df(dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< bool >::type want_crps(want_crpsSEXP);
    Rcpp::traits::input_parameter< bool >::type want_logscore(want_logscoreSEXP);
    Rcpp::traits::input_parameter< bool >::type want_cdf(want_cdfSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    Rcpp::traits::input_parameter< int >::type subdivisions(subdivisionsSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(score_mixture_cpp(y, mean, var, df, w, probs, want_crps, want_logscore, want_cdf, rel_tol, subdivisions, ncores));
    return rcpp_result_gen;
END_RCPP
}
// fingerprint_cpp
std::string fingerprint_cpp(SEXP num, Rcpp::CharacterVector chr);
RcppExport SEXP _ResTree_fingerprint_cpp(SEXP numSEXP, SEXP chrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type num(numSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type chr(chrSEXP);
    rcpp_result_gen = Rcpp::wrap(fingerprint_cpp(num, chr));
    return rcpp_result_gen;
END_RCPP
}
// smc_engine_info_cpp
Rcpp::List smc_engine_info_cpp(SEXP handle);
RcppExport SEXP _ResTree_smc_engine_info_cpp(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(smc_engine_info_cpp(handle));
    return rcpp_result_gen;
END_RCPP
}
// capabilities_cpp
Rcpp::List capabilities_cpp();
RcppExport SEXP _ResTree_capabilities_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(capabilities_cpp());
    return rcpp_result_gen;
END_RCPP
}
// thread_policy_cpp
Rcpp::List thread_policy_cpp(int request, bool warn);
RcppExport SEXP _ResTree_thread_policy_cpp(SEXP requestSEXP, SEXP warnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type request(requestSEXP);
    Rcpp::traits::input_parameter< bool >::type warn(warnSEXP);
    rcpp_result_gen = Rcpp::wrap(thread_policy_cpp(request, warn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ResTree_fixed_tree_geometry_cpp", (DL_FUNC) &_ResTree_fixed_tree_geometry_cpp, 7},
    {"_ResTree_full_tree_validity_cpp", (DL_FUNC) &_ResTree_full_tree_validity_cpp, 1},
    {"_ResTree_full_loglik_cache_info_cpp", (DL_FUNC) &_ResTree_full_loglik_cache_info_cpp, 1},
    {"_ResTree_fixed_tree_fit_cpp", (DL_FUNC) &_ResTree_fixed_tree_fit_cpp, 5},
    {"_ResTree_full_fit_engine_new_cpp", (DL_FUNC) &_ResTree_full_fit_engine_new_cpp, 3},
    {"_ResTree_full_fit_engine_eval_cpp", (DL_FUNC) &_ResTree_full_fit_engine_eval_cpp, 4},
    {"_ResTree_full_fit_engine_release_cpp", (DL_FUNC) &_ResTree_full_fit_engine_release_cpp, 1},
    {"_ResTree_find_neigh", (DL_FUNC) &_ResTree_find_neigh, 2},
    {"_ResTree_smc_engine_pmmh_cpp", (DL_FUNC) &_ResTree_smc_engine_pmmh_cpp, 18},
    {"_ResTree_pmmh_predict_cpp", (DL_FUNC) &_ResTree_pmmh_predict_cpp, 7},
    {"_ResTree_smc_sample_cpp", (DL_FUNC) &_ResTree_smc_sample_cpp, 9},
    {"_ResTree_smc_engine_new_cpp", (DL_FUNC) &_ResTree_smc_engine_new_cpp, 10},
    {"_ResTree_smc_engine_logZ_cpp", (DL_FUNC) &_ResTree_smc_engine_logZ_cpp, 4},
    {"_ResTree_smc_engine_save_cpp", (DL_FUNC) &_ResTree_smc_engine_save_cpp, 1},
    {"_ResTree_smc_engine_restore_cpp", (DL_FUNC) &_ResTree_smc_engine_restore_cpp, 1},
    {"_ResTree_smc_engine_release_cpp", (DL_FUNC) &_ResTree_smc_engine_release_cpp, 1},
    {"_ResTree_predict_state_cpp", (DL_FUNC) &_ResTree_predict_state_cpp, 7},
    {"_ResTree_rebuild_state_cpp", (DL_FUNC) &_ResTree_rebuild_state_cpp, 5},
    {"_ResTree_rebuild_nodes_cpp", (DL_FUNC) &_ResTree_rebuild_nodes_cpp, 4},
    {"_ResTree_predict_structures_cpp", (DL_FUNC) &_ResTree_predict_structures_cpp, 9},
    {"_ResTree_mixture_moments_cpp", (DL_FUNC) &_ResTree_mixture_moments_cpp, 3},
    {"_ResTree_restree_loglik", (DL_FUNC) &_ResTree_restree_loglik, 10},
    {"_ResTree_score_mixture_cpp", (DL_FUNC) &_ResTree_score_mixture_cpp, 12},
    {"_ResTree_fingerprint_cpp", (DL_FUNC) &_ResTree_fingerprint_cpp, 2},
    {"_ResTree_smc_engine_info_cpp", (DL_FUNC) &_ResTree_smc_engine_info_cpp, 1},
    {"_ResTree_capabilities_cpp", (DL_FUNC) &_ResTree_capabilities_cpp, 0},
    {"_ResTree_thread_policy_cpp", (DL_FUNC) &_ResTree_thread_policy_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ResTree(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
