# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fixed_tree_geometry_cpp <- function(x, depth, r, design, cut_method, seed = 42L, ncores = 1L) {
    .Call(`_ResTree_fixed_tree_geometry_cpp`, x, depth, r, design, cut_method, seed, ncores)
}

full_tree_validity_cpp <- function(model) {
    .Call(`_ResTree_full_tree_validity_cpp`, model)
}

full_loglik_cache_info_cpp <- function(model) {
    .Call(`_ResTree_full_loglik_cache_info_cpp`, model)
}

fixed_tree_fit_cpp <- function(model, theta, input_new, output_new = NULL, ncores = 1L) {
    .Call(`_ResTree_fixed_tree_fit_cpp`, model, theta, input_new, output_new, ncores)
}

full_fit_engine_new_cpp <- function(model, theta, ncores = 1L) {
    .Call(`_ResTree_full_fit_engine_new_cpp`, model, theta, ncores)
}

full_fit_engine_eval_cpp <- function(handle, theta, input_new, output_new = NULL) {
    .Call(`_ResTree_full_fit_engine_eval_cpp`, handle, theta, input_new, output_new)
}

full_fit_engine_release_cpp <- function(handle) {
    invisible(.Call(`_ResTree_full_fit_engine_release_cpp`, handle))
}

find_neigh <- function(input, r_knot) {
    .Call(`_ResTree_find_neigh`, input, r_knot)
}

smc_engine_pmmh_cpp <- function(handle, model, theta0, u0, n_iter, burnin, prop_sd, sig2_moves, blocked, prior, adapt, target_accept, seed, ncores, verbose, input_new = NULL, output_new = NULL, point_estimate = "median") {
    .Call(`_ResTree_smc_engine_pmmh_cpp`, handle, model, theta0, u0, n_iter, burnin, prop_sd, sig2_moves, blocked, prior, adapt, target_accept, seed, ncores, verbose, input_new, output_new, point_estimate)
}

pmmh_predict_cpp <- function(model, theta, chain, history, input_new, output_new = NULL, ncores = 1L) {
    .Call(`_ResTree_pmmh_predict_cpp`, model, theta, chain, history, input_new, output_new, ncores)
}

smc_sample_cpp <- function(model, theta, n_particles, seed = 42L, ncores = 1L, temper_alpha = 1.0, resampling = "stratified", input_new = NULL, output_new = NULL) {
    .Call(`_ResTree_smc_sample_cpp`, model, theta, n_particles, seed, ncores, temper_alpha, resampling, input_new, output_new)
}

smc_engine_new_cpp <- function(model, n_particles, resampling, temper_alpha, ncores, path_cache_mb = 256.0, keep_cache_levels = 2L, keep_cache_mb = 512.0, task_budget_mb = 512.0, level_cache_mb = 512.0) {
    .Call(`_ResTree_smc_engine_new_cpp`, model, n_particles, resampling, temper_alpha, ncores, path_cache_mb, keep_cache_levels, keep_cache_mb, task_budget_mb, level_cache_mb)
}

smc_engine_logZ_cpp <- function(handle, theta, seed, diagnostics = TRUE) {
    .Call(`_ResTree_smc_engine_logZ_cpp`, handle, theta, seed, diagnostics)
}

smc_engine_save_cpp <- function(handle) {
    invisible(.Call(`_ResTree_smc_engine_save_cpp`, handle))
}

smc_engine_restore_cpp <- function(handle) {
    .Call(`_ResTree_smc_engine_restore_cpp`, handle)
}

smc_engine_release_cpp <- function(handle) {
    invisible(.Call(`_ResTree_smc_engine_release_cpp`, handle))
}

predict_state_cpp <- function(state, input_new, distinct_rep, w_distinct, sig2, output_new = NULL, ncores = 1L) {
    .Call(`_ResTree_predict_state_cpp`, state, input_new, distinct_rep, w_distinct, sig2, output_new, ncores)
}

rebuild_state_cpp <- function(model, theta, S, J, cuts) {
    .Call(`_ResTree_rebuild_state_cpp`, model, theta, S, J, cuts)
}

rebuild_nodes_cpp <- function(model, theta, nodes, K) {
    .Call(`_ResTree_rebuild_nodes_cpp`, model, theta, nodes, K)
}

predict_structures_cpp <- function(model, theta, input_new, S, J, cuts, w, output_new = NULL, ncores = 1L) {
    .Call(`_ResTree_predict_structures_cpp`, model, theta, input_new, S, J, cuts, w, output_new, ncores)
}

mixture_moments_cpp <- function(mean, variance, w) {
    .Call(`_ResTree_mixture_moments_cpp`, mean, variance, w)
}

#' Log-likelihood of a residual-tree model at known covariance parameters
#'
#' Evaluates \eqn{\log p(y \mid \theta)} for the model specified by a
#' \code{\link{restree_model}} object at the covariance parameters
#' \code{theta}, and returns it as a single number:
#' \itemize{
#'   \item \code{leaf_model = "Full"}: one generated fixed tree (split
#'     while \eqn{n > r}, extending \code{depth} as needed, split dimension cycling over the
#'     coordinates, cuts from the model's \code{cut_method}) --
#'     \eqn{\log p(y \mid T, \theta)}. It is the exact dense GP
#'     log-likelihood when the root holds all rows, \code{n <= r}; use
#'     \code{r = nrow(x)} for that reference. Requesting \code{depth = 0}
#'     alone does not prevent Full from splitting.
#'   \item \code{leaf_model = "PP"} or \code{"WN"}: the tree is inferred by
#'     the sequential Monte Carlo sampler and averaged out under the model's
#'     Chipman--George--McCulloch prior, \eqn{\log Z(\theta) = \log \sum_T
#'     p(T)\, p(y \mid T, \theta)}; \eqn{\exp} of the estimate is unbiased
#'     for \eqn{Z(\theta)} at any particle count.
#'   \item any leaf model with \code{tree} supplied (a \code{list(S, J,
#'     cuts)} in the matrix convention of
#'     \code{\link{restree_trees}(fit, form = "matrix")}, e.g. one
#'     column of it, or the MAP tree of a fit): \eqn{\log p(y \mid T,
#'     \theta)} for that fixed tree.
#' }
#' \code{PP} and \code{WN} split adaptively: a node with fewer than
#' \code{r} observations may still split, spending all its rows as knots
#' (for \code{WN} the split is scored as the dense Gaussian knot block, the
#' convention shared by \code{\link{restree_fit}}).  A supplied \code{tree}
#' is rescored with \eqn{r_v = \min(r, n_v)} knots at every split, whatever
#' the leaf model. A supplied Full tree cannot stop with more than
#' \code{r} rows in a terminal; oversized terminals raise an error.
#'
#' Full returns the likelihood of its residual-tree covariance, not in
#' general the dense GP likelihood. PP/WN evidence targets their own
#' tree-prior mixtures, not a posterior-weighted average of tree likelihoods.
#' The log of an unbiased evidence estimate is not itself unbiased. Neither
#' tree averaging nor greater depth guarantees a closer dense-GP approximation.
#'
#' WN depth zero always specifies one WN leaf, even when \code{n > r}.
#' For positive depth, WN has no structural depth boundary: every nonempty node
#' compares stopping with splitting at every level, and a node with \code{n <= r}
#' spends all \code{n} rows as knots (an empty residual leaf) and still competes
#' its split with the stop. The realized WN tree therefore grows past the initial
#' depth as the data need. PP keeps its depth cap; Full uses its separate
#' size-controlled fixed tree without SMC.
#' A WN split beyond the representational limit (realized depth 25) raises an
#' error, also in EB/PMMH; it is never silently stopped.
#'
#' Model-based likelihood computation is compiled; data validation occurs
#' when model and theta objects are built. Fitted root-WN MLE evaluations
#' additionally verify their fitted-state record before reading the fitted mean.
#' The compiled entry still checks its inputs. Repeated Full calls reuse the
#' stored geometry through an internal native cache. Exact comparisons of the
#' data and geometry payload invalidate it after edits; a serialized pointer
#' rebuilds lazily. Covariance factors and likelihoods are always recomputed.
#' Repeated PP/WN calls run a fresh SMC; EB/PMMH use fit-local persistent engines.
#'
#' @inheritSection restree_model Leaf models
#' @param model a \code{\link{restree_model}} (or a fitted \code{restree},
#'   whose model slots are used). For a fitted depth-zero WN MLE,
#'   evaluates the iid Gaussian likelihood using the fitted mean and
#'   \code{theta$sig2} as its variance. An unfitted WN model retains the
#'   conjugate leaf marginal used by the Bayesian/SMC interfaces.
#' @param theta a \code{\link{restree_theta}} object, or a named list with
#'   the same fields.
#' @param tree \code{NULL}, or a \code{list(S, J, cuts)} with one entry per
#'   internal-node position (\code{2^depth} entries; \code{S}: 0 = split,
#'   1 = terminal, \code{NA} = unreachable). For WN with positive model
#'   depth, the array depth may
#'   exceed the model's supplied depth. All three models also accept
#'   \code{list(nodes = tab)}, where \code{tab} is one tree's rows from
#'   \code{restree_trees(fit)$nodes} (id, split, J, cut). This sparse form
#'   avoids allocating depth-sized arrays, including for nested PP. Include
#'   every nonempty node, including terminal nodes at PP's depth cap. PP
#'   cannot split at or beyond its cap; positive-depth WN remains open up to
#'   its representation limit. Matrix input remains supported.
#' @param nparticles SMC particles (PP / WN with \code{tree = NULL});
#'   \code{NULL} (default) uses \eqn{100\,\mathrm{depth}} for both PP and
#'   WN, using the configured model depth, not the realized WN tree depth.
#'   This is the rule of \code{\link{restree_fit}}. Root-only models use one
#'   particle. Explicit \code{nparticles} values override the default for
#'   positive depth. Full and supplied-tree likelihoods do not use SMC.
#' @param resampling \code{"stratified"} or \code{"multinomial"}.
#' @param temper_alpha tempering exponent of the SMC weights; \code{1} is
#'   the plain evidence estimator.
#' @param seed random seed of the SMC (\code{PP} / \code{WN}).  A \code{Full}
#'   model's tree is part of the model (built by \code{restree_model()} from
#'   its own \code{seed}), so this argument does not affect it.
#' @param ncores positive thread request. Uses the allocation-bounded engine/
#'   Eigen policy of \code{\link{restree_fit}}; without OpenMP execution is serial.
#' @param verify if \code{TRUE}, every distinct sampled tree is rescored by
#'   a separate fixed-structure traversal (sharing numerical kernels) and the call errors on any
#'   disagreement above 1e-6. This development validation can be substantially
#'   more expensive than an ordinary sampler run and is off by default.
#'   PP and WN verification use reached-node records, without depth-sized
#'   matrices. Nested PP carries candidate rows along the recursion.
#'   Applies only to sampled PP/WN trees: Full, depth-zero and supplied-tree
#'   calls do not run this check. It does not establish exact integrated
#'   evidence or accuracy relative to the original dense GP.
#' @param diagnostics if \code{TRUE}, the returned number carries the attributes
#'   described under Value. The default \code{FALSE} returns the bare number and
#'   skips optional distinct-tree grouping, weighted knot counts and level-table
#'   export. With both flags false, it also skips realized-tree score reconstruction.
#' @return A single number: the log-likelihood (fixed tree) or log evidence
#'   (SMC); with \code{diagnostics = TRUE} it carries the attributes \code{n_knot} (internal knots spent; the
#'   particle-weighted mean for SMC) and, for SMC, \code{ess} (final
#'   effective sample size), \code{n_distinct_trees}, \code{n_resample}
#'   \code{root_split_weight} (estimated posterior root-split mass),
#'   \code{root_split_fraction} (unweighted particle fraction), and
#'   \code{level_diag}, a data frame with one row per tree level (the
#'   level-end \code{ess} before and after resampling, \code{resampled},
#'   \code{max_weight}, the level's \code{logZ_increment} and the number of
#'   distinct node-paths \code{n_paths}); \code{\link{restree_diagnostics}} collects
#'   it over replicate runs.
#' @examples
#' set.seed(1)
#' n <- 300; X <- matrix(runif(2 * n), n, 2)
#' y <- sin(4 * pi * X[, 1]) + rnorm(n, sd = 0.3)
#' th <- restree_theta(sig2 = 1, range = 0.2, nugget = 0.1)
#'
#' ## exact GP log-likelihood: all training rows fit in the Full root
#' restree_loglik(restree_model(X, y, depth = 0, r = nrow(X), leaf_model = "Full"), th)
#' ## size-constrained Full approximation, initially allocating depth 3
#' restree_loglik(restree_model(X, y, depth = 3, r = 15, leaf_model = "Full"), th)
#' ## PP leaves: tree inferred and averaged out by SMC
#' m <- restree_model(X, y, depth = 3, r = 15, leaf_model = "PP")
#' restree_loglik(m, th, nparticles = 100, seed = 7)
#' @export
restree_loglik <- function(model, theta, tree = NULL, nparticles = NULL, resampling = "stratified", temper_alpha = 1.0, seed = 42L, ncores = 1L, verify = FALSE, diagnostics = FALSE) {
    .Call(`_ResTree_restree_loglik`, model, theta, tree, nparticles, resampling, temper_alpha, seed, ncores, verify, diagnostics)
}

score_mixture_cpp <- function(y, mean, var, df, w, probs, want_crps, want_logscore, want_cdf, rel_tol, subdivisions, ncores) {
    .Call(`_ResTree_score_mixture_cpp`, y, mean, var, df, w, probs, want_crps, want_logscore, want_cdf, rel_tol, subdivisions, ncores)
}

fingerprint_cpp <- function(num, chr) {
    .Call(`_ResTree_fingerprint_cpp`, num, chr)
}

smc_engine_info_cpp <- function(handle) {
    .Call(`_ResTree_smc_engine_info_cpp`, handle)
}

capabilities_cpp <- function() {
    .Call(`_ResTree_capabilities_cpp`)
}

thread_policy_cpp <- function(request, warn = TRUE) {
    .Call(`_ResTree_thread_policy_cpp`, request, warn)
}

